### ISSUE TITLE
rails4 create record failing

### ISSUE THREAD

**Issue by danil-z** [globalize/globalize#263]
I'm wondering why i'm not able to create a record if i use _translates_  method at model?

_rails Console_

``` ruby
Loading development environment (Rails 4.0.0)
Switch to inspect mode.
>> p = Page.new
#<Page id: nil, title: nil, slug: nil, footer: nil, body: nil, meta_keywords: nil, meta_description: nil, created_at: nil, updated_at: nil>

>> p.title = 'abc'
"abc"

>> p.save
   (0.3ms)  BEGIN
  Page::Translation Exists (0.9ms)  SELECT 1 AS one FROM "page_translations" WHERE ("page_translations"."title" = 'abc' AND "page_translations"."locale" = 'ru') LIMIT 1
  SQL (2.6ms)  INSERT INTO "pages" ("created_at", "title", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["created_at", Sat, 17 Aug 2013 07:11:17 UTC +00:00], ["title", "abc"], ["updated_at", Sat, 17 Aug 2013 07:11:17 UTC +00:00]]
  SQL (1.2ms)  INSERT INTO "page_translations" ("created_at", "locale", "title", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["created_at", Sat, 17 Aug 2013 07:11:17 UTC +00:00], ["locale", "ru"], ["title", "abc"], ["updated_at", Sat, 17 Aug 2013 07:11:17 UTC +00:00]]
PG::NotNullViolation: ERROR:  null value in column "page_id" violates not-null constraint
DETAIL:  Failing row contains (7, null, ru, 2013-08-17 07:11:17.374907, 2013-08-17 07:11:17.374907, abc, null, null, null, null).
: INSERT INTO "page_translations" ("created_at", "locale", "title", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "page_id" violates not-null constraint
DETAIL:  Failing row contains (7, null, ru, 2013-08-17 07:11:17.374907, 2013-08-17 07:11:17.374907, abc, null, null, null, null).
: INSERT INTO "page_translations" ("created_at", "locale", "title", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:780:in `get_last_result'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:780:in `exec_cache'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:139:in `block in exec_query'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:425:in `block in log'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:420:in `log'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:183:in `exec_insert'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:96:in `insert'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/relation.rb:76:in `insert'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/persistence.rb:498:in `create_record'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:78:in `create_record'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:303:in `block in create_record'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__1146646467404712261__create__callbacks'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
... 34 levels...
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block in save'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/transactions.rb:269:in `save'
    from (irb):5
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /Users/danil/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
    from /Users/danil/Sites/aride/bin/rails:4:in `require'
    from /Users/danil/Sites/aride/bin/rails:4:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'
```

_Gemfile_

``` ruby
gem 'paper_trail', github: 'airblade/paper_trail', branch: 'rails4'
gem 'globalize3', github: 'svenfuchs/globalize3', branch: 'rails4', ref: 'ffb5c771b9'
gem 'protected_attributes'
```

_app/models/page.rb_

``` ruby
class Page < ActiveRecord::Base
  attr_accessible :title, :body, :footer, :meta_keywords, :meta_description
  validates :title, presence: true, uniqueness: true
  translates :title, :body, :slug, :meta_keywords, :meta_description
end
```

_db/migrate/123_create_pages.rb_

``` ruby
class CreatePages < ActiveRecord::Migration
  def up
    create_table :pages do |t|
      t.string :title
      t.string :slug
      t.boolean :footer
      t.text :body
      t.string :meta_keywords
      t.string :meta_description

      t.timestamps
    end
    add_index :pages, :title
    add_index :pages, :slug
    add_index :pages, :footer
    Page.create_translation_table! :title => :string, :slug => :string, :body => :text, :meta_keywords => :string, :meta_description => :string
  end

  def down
    drop_table :pages
    Page.drop_translation_table!
  end
end
```

**Comment by romul** [comment]
Same here. Rails 4.2.0 and Globalize 5.0.1
```
PG::NotNullViolation: ERROR:  null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (8, null, 2015-02-23 14:23:51.483076, 2015-02-23 14:23:51.483076, 0).
```

**Comment by KeithYJohnson** [comment]
@romul just curious did you ever get this sorted out?

**Comment by romul** [comment]
@KeithYJohnson As I know, the only way is to remove not-null constraint for globalized columns.

**Comment by KeithYJohnson** [comment]
@romul Thanks yeah I wound up doing something like

```ruby
class RemoveNullConstraintsFromTranslationTables < ActiveRecord::Migration
  def up
    change_column :table_name, :whatever_id, :integer, null: true
