### ISSUE TITLE
Rake db:migrate fails (Globalize 5.0.0)

### ISSUE THREAD

**Issue by rhazegh** [globalize/globalize#406]
I am using Globalize 5.0.0 (I have included the Gemfile.lock at the bottom of the issue) and have a single attribute to translate on my active record model. (BTW, this is not a Rails project).
```ruby
require 'active_record'
require 'globalize'

class Activity < ActiveRecord::Base
  translates :title
end
```

`rake db:migrate` fails when loading this active record model. Basically it fails executing the first line of the `Rakefile` (pasted below). Here is error message I get when I issue `rake db:migrate --trace`

```
$ rake db:migrate --trace
rake aborted!
ActiveRecord::ConnectionNotEstablished: No connection pool for Activity
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:564:in `retrieve_connection'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activerecord-4.2.0/lib/active_record/attributes.rb:91:in `columns'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activerecord-4.2.0/lib/active_record/attributes.rb:96:in `columns_hash'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:66:in `serializer_for_attribute'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:54:in `enable_serializable_attribute'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:32:in `block in allow_translation_of_attributes'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:30:in `each'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:30:in `allow_translation_of_attributes'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/globalize-5.0.0/lib/globalize/active_record/act_macro.rb:13:in `translates'
/Users/ramin/projects/myproject/app/models/activity.rb:19:in `<class:Activity>'
/Users/ramin/projects/myproject/app/models/activity.rb:18:in `<top (required)>'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/ramin/projects/myproject/Rakefile:1:in `block in <top (required)>'
/Users/ramin/projects/myproject/Rakefile:1:in `each'
/Users/ramin/projects/myproject/Rakefile:1:in `<top (required)>'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/ramin/.rvm/gems/ruby-2.1.2@myroject/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/ramin/.rvm/rubies/ruby-2.1.2/bin/rake:33:in `<main>'
```
### Rakefile
```ruby
Dir[File.join(File.dirname(__FILE__), 'app/models', '*.rb')].each {|file| require file }

# Needed to overwrite the already existing Rake task "load_config"
class Rake::Task
  def overwrite(&block)
    @actions.clear
    enhance(&block)
  end
end

# Load the ActiveRecord tasks
spec = Gem::Specification.find_by_name('activerecord')
load File.join(spec.gem_dir, 'lib', 'active_record', 'railties', 'databases.rake')

# Overwrite the load config to your needs
Rake::Task['db:load_config'].overwrite do
  configuration = YAML::load(IO.read('config/database.yml'))

  ActiveRecord::Base.configurations = ActiveRecord::Tasks::DatabaseTasks.database_configuration = configuration
  ActiveRecord::Tasks::DatabaseTasks.db_dir = 'db'
  ActiveRecord::Tasks::DatabaseTasks.env    = 'development'
end

# Migrations need an environment with an already established database connection
task :environment => ['db:load_config'] do
  ActiveRecord::Base.establish_connection ActiveRecord::Tasks::DatabaseTasks.database_configuration[ActiveRecord::Tasks::DatabaseTasks.env]
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    annotate (2.6.5)
      activerecord (>= 2.3.0)
      rake (>= 0.8.7)
    arel (6.0.0)
    builder (3.2.2)
    faraday (0.9.1)
      multipart-post (>= 1.2, < 3)
    globalize (5.0.0)
      activemodel (>= 4.2.0, < 4.3)
      activerecord (>= 4.2.0, < 4.3)
    httparty (0.13.3)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    json (1.8.2)
    jwt (1.2.1)
    mini_portile (0.6.2)
    minitest (5.5.1)
    multi_json (1.10.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    pg (0.18.1)
    rack (1.6.0)
    rake (10.4.2)
    recursive-open-struct (0.5.0)
    thread_safe (0.3.4)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activemodel
  activerecord
  annotate
  faraday
  globalize (~> 5.0.0)
  httparty
  nokogiri
  oauth2
  pg
  rake
  recursive-open-struct
```

**Comment by ariel201286** [comment]
I have the same problem

**Comment by simi** [comment]
Hello @rhazegh and @ariel201286.

Are you using `serialized` in your models? Can you try latest master? I think https://github.com/globalize/globalize/commit/44e79fbb2ba08c8fed3ddb673e899d5aa248746c can solve your problems. Actually it is not released since it needs a little refactoring. But I'll dive into that really soon.

**Comment by rhazegh** [comment]
Switched to the latest master and now I get another error message:

```
$ rake db:migrate --trace
rake aborted!
cannot load such file -- globalize
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ramin/.rvm/gems/ruby-2.1.2@myproject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/ramin/.rvm/gems/ruby-2.1.2@myproject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ramin/.rvm/gems/ruby-2.1.2@myproject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/ramin/projects/myproject/app/models/activity.rb:16:in `<top (required)>'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/ramin/.rvm/gems/ruby-2.1.2@myproject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/ramin/.rvm/gems/ruby-2.1.2@myproject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ramin/.rvm/gems/ruby-2.1.2@myproject/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/ramin/projects/myproject/Rakefile:1:in `block in <top (required)>'
/Users/ramin/projects/myproject/Rakefile:1:in `each'
/Users/ramin/projects/myproject/Rakefile:1:in `<top (required)>'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/rake_module.rb:25:in `load_rakefile'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:637:in `raw_load_rakefile'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:94:in `block in load_rakefile'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:93:in `load_rakefile'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:77:in `block in run'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:165:in `standard_exception_handling'
/Users/ramin/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/Users/ramin/.rvm/rubies/ruby-2.1.2/bin/rake:33:in `<main>'
```

Gemfile.lock diff:

```
GIT
remote: git@github.com:globalize/globalize.git
revision: 7488d920b250a1a2a9c202156d496c38c6e97bba

...

globalize (5.0.0)
  activemodel (>= 4.2.0, < 4.3)
  activerecord (>= 4.2.0, < 4.3)
```

**Comment by simi** [comment]
You need to add `reqiure 'bundler/setup'` on the top of the script probably.

**Comment by rhazegh** [comment]
@simi that solved the problem :+1: Thanks a lot.

**Comment by JDutil** [comment]
The https://github.com/spree-contrib/spree_i18n project is broken on Rails 4.2 w/Globalize 5.0.0 with similar error.  Anytime we try to build the test app I hit an error that database table doesn't exist coming from the first models `translates` method call.

I just tried bundling globalize from source to see if  https://github.com/globalize/globalize/commit/44e79fbb2ba08c8fed3ddb673e899d5aa248746c would help and the errors appear to be resolved now for me as well.

Any chance we can get a 5.0.1 release @simi ?

**Comment by parndt** [comment]
Fine with me, as long as it's backward compatible and we don't need `5.1.0` instead?

**Comment by simi** [comment]
@parndt wait for release few minutes please. I submit patch to make my patch dignified.

**Comment by simi** [comment]
Time to release @parndt @shioyama 5.0.1!

**Comment by simi** [comment]
@rhazegh 5.0.1 pushed. Can you confirm it works please?

**Comment by JDutil** [comment]
Thanks!

**Comment by rhazegh** [comment]
@simi yes, 5.0.1 is working for me. Thank you.
