### ISSUE TITLE
Doesn't work add_translation_fields method

### ISSUE THREAD

**Issue by daisuke-3** [globalize/globalize#425]
I couldn't add translation field.

The migration file is below:

```
class AddAttributesToVenue < ActiveRecord::Migration
  def up
    Venue.add_translation_fields!(
      reservation: :string
    )
  end

  def down
    remove_column :venue_translations, :reservation
  end
e
```

After that, the error has occoured.

```
$ rake db:migrate
== 20150301035348 AddAttributesToVenue: migrating =============================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Missing translated field :reservation/Users/daisuke_3/Documents/quchy/quchy/db/migrate/20150301035348_add_attributes_to_venue.rb:3:in `up'
Globalize::ActiveRecord::Exceptions::BadFieldName: Missing translated field :reservation
/Users/daisuke_3/Documents/quchy/quchy/db/migrate/20150301035348_add_attributes_to_venue.rb:3:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Then it worked when I fixed migration.rb.

before

```
        def validate_translated_fields
          fields.each do |name, options|
            raise BadFieldName.new(name) unless valid_field_name?(name)
            type = (options.is_a? Hash) ? options[:type] : options
            raise BadFieldType.new(name, type) unless valid_field_type?(name, type)
          end
        end
```

after

```
        def validate_translated_fields
          fields.each do |name, options|
            raise BadFieldName.new(name) if valid_field_name?(name)
            type = (options.is_a? Hash) ? options[:type] : options
            raise BadFieldType.new(name, type) unless valid_field_type?(name, type)
          end
        end
```

Is this bug?

**Comment by daisuke-3** [comment]
Sorry.

It resolved.
The model has added translates keyword "reservation".

It works when I added translates to the model.

```
  translates :name, :hours, :holidays, :address, :city, :state, :cross_street, :statement, :description, :reservation
```
