### ISSUE TITLE
translates definition causes postgres to fail

### ISSUE THREAD

**Issue by casiodk** [globalize/globalize#573]
Just installed globalize

my gem list

```
active_model_serializers (0.10.2)
activejob (5.0.0.1)
activemodel (5.0.0.1)
activemodel-serializers-xml (1.0.1)
activerecord (5.0.0.1)
activesupport (5.0.0.1)
globalize (5.1.0)
pg (0.19.0)
```

my migration

```
class CreatePlanFeatures < ActiveRecord::Migration[5.0]
  def change
    create_table :plan_features do |t|
      t.integer :position

      t.timestamps
    end

    reversible do |dir|
      dir.up do
        PlanFeature.create_translation_table! name: :string, description: :string
      end

      dir.down do
        PlanFeature.drop_translation_table!
      end
    end
  end
end
```

when i define translates in my model i get this error when running my tests

```
 bin/rspec
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/nicolaiseerup/Sites/Soundtracktor/soundtracktor-api/config/environment.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at /Users/nicolaiseerup/Sites/Soundtracktor/soundtracktor-api/spec/rails_helper.rb:9)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at /Users/nicolaiseerup/Sites/Soundtracktor/soundtracktor-api/app/controllers/application_controller.rb:2)
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 42764
Daemon has started successfully

An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:truncation)

ActiveRecord::StatementInvalid:
  PG::ConnectionBad: PQsocket() can't get socket descriptor:           SELECT schemaname || '.' || tablename
            FROM pg_tables
            WHERE
              tablename !~ '_prt_' AND
              tablename <> 'schema_migrations' AND
              schemaname = ANY (current_schemas(false))
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:33:in `select_rows'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/truncation.rb:190:in `tables_with_schema'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/truncation.rb:165:in `database_cleaner_table_cache'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/truncation.rb:247:in `tables_to_truncate'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/truncation.rb:239:in `block in clean'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:22:in `disable_referential_integrity'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/active_record/truncation.rb:235:in `clean'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:46:in `clean_with'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:91:in `block in clean_with'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:91:in `each'
# /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:91:in `clean_with'
# ./spec/rails_helper.rb:42:in `block (2 levels) in <top (required)>'
# ------------------
# --- Caused by: ---
# PG::ConnectionBad:
#   PQsocket() can't get socket descriptor
#   /Users/nicolaiseerup/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'


Top 0 slowest examples (0 seconds, 0.0% of total time):

Finished in 5.47 seconds (files took 4.73 seconds to load)
0 examples, 0 failures
```

when the translated fields are not defined in the model everything runs as expected

**Comment by casiodk** [comment]
It seems these two lines

`
StripeMock.spawn_server
StripeMock.start_client
`
 from this gem https://github.com/rebelidealist/stripe-ruby-mock

is causing the error
